DROP DATABASE IF EXISTS c207;

CREATE DATABASE c207;

USE c207;

CREATE TABLE DEPARTAMENTO (
  DNOME varchar(45) NOT NULL,
  DNUMERO integer NOT NULL,
  DATAINICIO date,
  SSN_Empregado bigint,
  PRIMARY KEY (`DNumero`)
) ;

CREATE TABLE EMPREGADO (
  PNOME varchar(15) NOT NULL,
  MINICIAL char,
  UNOME varchar(15) NOT NULL,
  SSN bigint NOT NULL,
  DATANASC date,
  ENDERECO varchar(80),
  SEXO char,
  SALARIO float,
  SSN_SUPERVISOR bigint,
  DNUMERO_DEPARTAMENTO integer NOT NULL,
  PRIMARY KEY (`SSN`),
  CONSTRAINT `fk1` 
  FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  CONSTRAINT `fk2` 
  FOREIGN KEY (SSN_SUPERVISOR) REFERENCES EMPREGADO (SSN)
  ON DELETE CASCADE
  ON UPDATE CASCADE
) ;


CREATE TABLE PROJETO(
	PNOME varchar(15) NOT NULL,
    PNUMERO integer NOT NULL,
    PLOCALIZACAO varchar(40),
    DNUMERO_DEPARTAMENTO integer,
    PRIMARY KEY(`PNUMERO`),
    CONSTRAINT `fk3` 
	FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
) ;

CREATE TABLE DEPENDENTE (
	SSN_EMPREGADO bigint NOT NULL,
    NOME_DEPENDENTE varchar(40) NOT NULL,
    SEXO varchar(1),
    DATANASC date,
    PARENTESCO varchar(15),
	PRIMARY KEY(`NOME_DEPENDENTE`,`SSN_EMPREGADO`),
    CONSTRAINT `fk4` 
	FOREIGN KEY (SSN_EMPREGADO) REFERENCES EMPREGADO (SSN)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE DEPTO_LOCALIZACOES (
	LNUMERO integer not null,
    DLOCALIZACAO varchar(40) not null,
    DNUMERO_DEPARTAMENTO int,
    PRIMARY KEY(`LNUMERO`),
	CONSTRAINT `fk5` 
	FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE TRABALHA_EM (
	SSN_EMPREGADO bigint NOT NULL,
    PNUMERO_PROJETO integer NOT NULL,
    HORAS time NOT NULL,
    PRIMARY KEY(`SSN_EMPREGADO`,`PNUMERO_PROJETO`),
    CONSTRAINT `fk6` 
	FOREIGN KEY (SSN_EMPREGADO) REFERENCES EMPREGADO (SSN)
    ON DELETE CASCADE
	ON UPDATE CASCADE,
    CONSTRAINT `fk7` 
	FOREIGN KEY (PNUMERO_PROJETO) REFERENCES PROJETO(PNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

#1
insert into DEPARTAMENTO(DNOME,DNUMERO,DATAINICIO) values ('rh',12,'2021-06-15');
insert into DEPARTAMENTO(DNOME,DNUMERO,DATAINICIO) values ('suporte',10,'2021-06-15');

#2
insert into DEPARTAMENTO(DNOME,DNUMERO) values ('financeiro',2);

#3
insert into EMPREGADO(PNOME,UNOME,SSN,DATANASC,DNUMERO_DEPARTAMENTO) values('Leo','Junior',123456789,'2021-06-15',10);
insert into EMPREGADO(PNOME,UNOME,SSN,DATANASC,DNUMERO_DEPARTAMENTO) values('Gabriel','Felicianno',1234567689,'2021-06-15',12);
insert into EMPREGADO(PNOME,MINICIAL,UNOME,SSN,DATANASC,ENDERECO,SEXO,SALARIO,SSN_SUPERVISOR,DNUMERO_DEPARTAMENTO) values
('Felipe','D','Heinz',12345123,'2021-06-15','Rua Major','M',12345.32,123456789,10),
('Maria','H','Lobato',1212321,'2021-06-15','Rua Major','F',1235.32,1234567689,12);

#4
insert into projeto(PNOME,PNUMERO) values
('pubg',2),
('free',3),
('explode',4);

#5
update EMPREGADO set SSN_SUPERVISOR = 123456789 where SSN =  12345123;
update EMPREGADO set SSN_SUPERVISOR = 123456789 where SSN =  1212321;
update EMPREGADO set SSN_SUPERVISOR = 123456789 where SSN =  1234567689;

#6
update DEPARTAMENTO set SSN_EMPREGADO = 876545645 where DNUMERO=10;
update DEPARTAMENTO set SSN_EMPREGADO = 3453647352 where DNUMERO=12;

#7

update projeto set PLOCALIZACAO = 'SENSE', DNUMERO_DEPARTAMENTO=10 where PNUMERO = 2;
update projeto set PLOCALIZACAO = 'JFL', DNUMERO_DEPARTAMENTO=12 where PNUMERO = 3;
update projeto set PLOCALIZACAO = 'INATEL', DNUMERO_DEPARTAMENTO=10 where PNUMERO = 4;

#8
delete from PROJETO where DNUMERO_DEPARTAMENTO=10;


#select * from DEPARTAMENTO;
#select * from EMPREGADO;
#select * from PROJETO;
