DROP DATABASE IF EXISTS c207;

CREATE DATABASE c207;

USE c207;

CREATE TABLE DEPARTAMENTO (
  DNOME varchar(45) NOT NULL,
  DNUMERO integer NOT NULL,
  DATAINICIO date,
  SSN_Empregado bigint,
  PRIMARY KEY (`DNumero`)
) ;

CREATE TABLE EMPREGADO (
  PNOME varchar(15) NOT NULL,
  MINICIAL char,
  UNOME varchar(15) NOT NULL,
  SSN bigint NOT NULL,
  DATANASC date,
  ENDERECO varchar(80),
  SEXO char,
  SALARIO float,
  SSN_SUPERVISOR bigint,
  DNUMERO_DEPARTAMENTO integer NOT NULL,
  PRIMARY KEY (`SSN`),
  CONSTRAINT `fk1` 
  FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  CONSTRAINT `fk2` 
  FOREIGN KEY (SSN_SUPERVISOR) REFERENCES EMPREGADO (SSN)
  ON DELETE CASCADE
  ON UPDATE CASCADE
) ;


CREATE TABLE PROJETO(
	PNOME varchar(15) NOT NULL,
    PNUMERO integer NOT NULL,
    PLOCALIZACAO varchar(40),
    DNUMERO_DEPARTAMENTO integer,
    PRIMARY KEY(`PNUMERO`),
    CONSTRAINT `fk3` 
	FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
) ;

CREATE TABLE DEPENDENTE (
	SSN_EMPREGADO bigint NOT NULL,
    NOME_DEPENDENTE varchar(40) NOT NULL,
    SEXO varchar(1),
    DATANASC date,
    PARENTESCO varchar(15),
	PRIMARY KEY(`NOME_DEPENDENTE`,`SSN_EMPREGADO`),
    CONSTRAINT `fk4` 
	FOREIGN KEY (SSN_EMPREGADO) REFERENCES EMPREGADO (SSN)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE DEPTO_LOCALIZACOES (
	LNUMERO integer not null,
    DLOCALIZACAO varchar(40) not null,
    DNUMERO_DEPARTAMENTO int,
    PRIMARY KEY(`LNUMERO`),
	CONSTRAINT `fk5` 
	FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES DEPARTAMENTO (DNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE TRABALHA_EM (
	SSN_EMPREGADO bigint NOT NULL,
    PNUMERO_PROJETO integer NOT NULL,
    HORAS time NOT NULL,
    PRIMARY KEY(`SSN_EMPREGADO`,`PNUMERO_PROJETO`),
    CONSTRAINT `fk6` 
	FOREIGN KEY (SSN_EMPREGADO) REFERENCES EMPREGADO (SSN)
    ON DELETE CASCADE
	ON UPDATE CASCADE,
    CONSTRAINT `fk7` 
	FOREIGN KEY (PNUMERO_PROJETO) REFERENCES PROJETO(PNUMERO)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);
#1
insert into DEPENDENTE(SSN_EMPREGADO,NOME_DEPENDENTE,SEXO,DATANASC,PARENTESCO) values
('123456789','Leo','M','2001-02-24','irmao'),
('1234567689','Gabriel','M','2001-02-23','irmao'),
('123456789','Felipe','M','2001-02-22','tio'),
('1234567689','Joao','M','2001-02-21','primo');

select distinct PARENTESCO from DEPENDENTE;

#2
insert into EMPREGADO(PNOME,UNOME,SSN,DATANASC,DNUMERO_DEPARTAMENTO,SEXO) values('Leandro','Junior',123456789,'2000-06-15',10,'M');
insert into EMPREGADO(PNOME,UNOME,SSN,DATANASC,DNUMERO_DEPARTAMENTO,SEXO) values('José','Felicianno',1234567689,'2001-06-15',12,'M');
insert into EMPREGADO(PNOME,MINICIAL,UNOME,SSN,DATANASC,ENDERECO,SEXO,SALARIO,SSN_SUPERVISOR,DNUMERO_DEPARTAMENTO) values
('Matheus','D','Heinz',12345123,'2010-06-15','Rua Major','M',1345.32,123456789,10),
('Maria','H','Lobato',1212321,'2002-06-15','Rua Major','F',1235.32,1234567689,12);

select UNOME,DATANASC from EMPREGADO where SEXO = 'M' order by DATANASC DESC;

#3
select NOME_DEPENDENTE, PNOME from DEPENDENTE inner join EMPREGADO on SSN_EMPREGADO = SSN; 

#4
update EMPREGADO set ENDERECO = 'Sao Paulo' where ssn=12345123;
update EMPREGADO set ENDERECO = 'Sao Paulo' where ssn=1212321;

insert into DEPARTAMENTO(DNOME,DNUMERO,DATAINICIO) values ('Engenharia',12,'2021-06-15');
insert into DEPARTAMENTO(DNOME,DNUMERO,DATAINICIO) values ('Engenharia',10,'2021-06-15');

select avg(SALARIO) from EMPREGADO inner join DEPARTAMENTO on DNUMERO_DEPARTAMENTO = DNUMERO where DNOME = 'ENGENHARIA' and ENDERECO like '%Sao Paulo%';

#5
update EMPREGADO set SALARIO = 10000 where SSN = 123456789;
update EMPREGADO set SALARIO = 10000 where SSN =1234567689;

select S.PNOME, E.PNOME, (S.SALARIO - E.SALARIO) from EMPREGADO as S
inner join EMPREGADO as E
on E.SSN_SUPERVISOR = S.SSN;
#6

insert into projeto(PNOME,PNUMERO) values
('pubg',2),
('free',3),
('explode',4);

insert into TRABALHA_EM(SSN_EMPREGADO,PNUMERO_PROJETO,HORAS) values
('123456789',2,'00:30:00'),
('1234567689',3,'00:20:00'),
('1234567689',4,'00:45:00');

select E.PNOME, P.PNOME, HORAS from EMPREGADO as E
inner join TRABALHA_EM
on SSN_EMPREGADO = SSN
inner join PROJETO as P
on PNUMERO_PROJETO = P.PNUMERO;

select * from EMPREGADO;
select * from TRABALHA_EM;